









#define SystemSevenOrLater 1
//#include "Types.r"
//#include "SysTypes.r"
//#include "AEUserTermTypes.r"
#include <Carbon/Carbon.r>

resource 'aete' (0,"Scripting terminology") {
0x1,
0x0,
0,
0,

{
	
	"Required Suite",       	
	"Terms that every application should support",	
	'reqd',         	
	1,      	
	1,    
		{
			
				"open",
				"Open the specified object(s)",
				'aevt',
				'odoc',
				'null',
				"",
					replyOptional,
					singleItem,
					notEnumerated,
					notTightBindingFunction,
					enumsAreConstants,
					enumListCanRepeat,
					replyIsValue,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					verbEvent,
					reserved,
					reserved,
					reserved,
				'obj ',
				"Objects to open. Can be a list of files or an object specifier.",
					directParamRequired,
					singleItem,
					notEnumerated,
					changesState,
					enumsAreConstants,
					enumListCanRepeat,
					directParamIsValue,
					directParamIsTarget,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
				{
					
						"from",
						'From',
						'FORK',
						"restrict to a particular fork (default is anyFork)",
							optional,
							singleItem,
							enumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"readOnly",
						'pRDO',
						'bool',
						"specify if the file should be opened in read-only mode (by default it is not)",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"quit",
				"Quit the application",
				'aevt',
				'quit',
				'null',
				"",
					replyOptional,
					singleItem,
					notEnumerated,
					notTightBindingFunction,
					enumsAreConstants,
					enumListCanRepeat,
					replyIsValue,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					verbEvent,
					reserved,
					reserved,
					reserved,
				'null',
				"",
					directParamOptional,
					singleItem,
					notEnumerated,
					changesState,
					enumsAreConstants,
					enumListCanRepeat,
					directParamIsValue,
					directParamIsTarget,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
				{
				}
			

		},

		{
		},

		{
		},

		{
		}
	,
	"Standard Suite",
	"Common terms for most applications",
	'CoRe',
	1,
	1,
		{
			
				"close",
				"Close an object",
				'core',
				'clos',
				'null',
				"",
					replyOptional,
					singleItem,
					notEnumerated,
					notTightBindingFunction,
					enumsAreConstants,
					enumListCanRepeat,
					replyIsValue,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					verbEvent,
					reserved,
					reserved,
					reserved,
				'obj ',
				"the objects to close",
					directParamRequired,
					singleItem,
					notEnumerated,
					changesState,
					enumsAreConstants,
					enumListCanRepeat,
					directParamIsValue,
					directParamIsTarget,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
				{
					
						"saving",
						'savo',
						'savo',
						"specifies whether or not changes should be saved before closing",
							optional,
							singleItem,
							enumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"count",
				"Return the number of elements of a particular class within an object",
				'core',
				'cnte',
				'long',
				"the number of elements",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"the object whose elements are to be counted",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"each",
						'kocl',
						'type',
						"the class of the elements to be counted",
							required,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
								paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"data size",
				"Return the size in bytes of an object",
				'core',
				'dsiz',
				'long',
				"the size of the object in bytes",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"the object whose data size is to be returned",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
				}
			,
				"exists",
				"Verify if an object exists",
				'core',
				'doex',
				'bool',
				"true if it exists, false if not",
					replyRequired,
					singleItem,
					notEnumerated,
					notTightBindingFunction,
					enumsAreConstants,
					enumListCanRepeat,
					replyIsValue,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					verbEvent,
					reserved,
					reserved,
					reserved,
				'null',
				"",
					directParamRequired,
					singleItem,
					notEnumerated,
					doesntChangeState,
					enumsAreConstants,
					enumListCanRepeat,
					directParamIsValue,
					directParamIsTarget,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
				{
				}
			,
				"get",
				"Get the data for an object",
				'core',
				'getd',
				'****',
				"The data from the object",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"the object whose data is to be returned",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
				}
			,
				"make",
				"Make a new element",
				'core',
				'crel',
				'obj ',
				"Object specifier for the new element",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'null',
				"",
				directParamOptional,
				singleItem,
				notEnumerated,
				changesState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"new",
						'kocl',
						'type',
						"the class of the new element",
							required,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"in",
						'insh',
						'obj ',
						"the container in which to create the new element (it must already exist)",
							required,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"with properties",
						'prdt',
						'reco',
						"properties of the element (for instance 'name', 'readOnly', 'fork')",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"with data",
						'data',
						'****',
						"the initial data for the new element",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"save",
				"save an object",
				'core',
				'save',
				'null',
				"",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"object to save",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"in",
						'kfil',
						'alis',
						"the file in which to save the object",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"as",
						'fltp',
						'FORK',
						"the fork in which to save the data (in a Save As operation)",
							optional,
							singleItem,
							enumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"revert",
				"Revert an object to the most recently saved version",
				'misc',
				'rvrt',
				'null',
				"",
					replyOptional,
					singleItem,
					notEnumerated,
					notTightBindingFunction,
					enumsAreConstants,
					enumListCanRepeat,
					replyIsValue,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					verbEvent,
					reserved,
					reserved,
					reserved,
				'obj ',
				"object to revert",
					directParamRequired,
					singleItem,
					notEnumerated,
					doesntChangeState,
					enumsAreConstants,
					enumListCanRepeat,
					directParamIsValue,
					directParamIsTarget,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
				{
				}
			,
				"set",
				"Set an object's data",
				'core',
				'setd',
				'null',
				"",
					replyOptional,
					singleItem,
					notEnumerated,
					notTightBindingFunction,
					enumsAreConstants,
					enumListCanRepeat,
					replyIsValue,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					verbEvent,
					reserved,
					reserved,
					reserved,
				'obj ',
				"the object to change",
					directParamRequired,
					singleItem,
					notEnumerated,
					changesState,
					enumsAreConstants,
					enumListCanRepeat,
					directParamIsValue,
					directParamIsTarget,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
				{
					
						"to",
						'data',
						'****',
						"the new value",
							required,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			

		},

		{
			
				"application",
				'capp',
				"the application",
				{
					
						"name",
						'pnam',
						'itxt',
						"Rezilla's name",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"version",
						'vers',
						'itxt',
						"the version of the application",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"inspector",
						'pINS',
						'InsW',
						"the inspector",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
					
						'cwin',
						{
							'indx',
							'name',
							'rang'}
					,
						'docu',
						{
							'indx',
							'name'}
					,
						'MapD',
						{
							'indx',
							'name'}
					,
						'cMAP',
						{
							'ID  '}
					
				}
			,
				"document",
				'docu',
				"A document",
				{
					
						"name",
						'pnam',
						'itxt',
						"the title of the document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"modified",
						'imod',
						'bool',
						"Has the document been modified since the last save?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"documents",
				'docu',
				"every document",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"window",
				'cwin',
				"a window",
				{
					
						"name",
						'pnam',
						'itxt',
						"the title of the window",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"index",
						'pidx',
						'long',
						"the number of the window",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"bounds",
						'pbnd',
						'qdrt',
						"the boundary rectangle for the window",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"closeable",
						'hclb',
						'bool',
						"does the window have a close box?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"titled",
						'ptit',
						'bool',
						"does the window have a title bar?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"floating",
						'isfl',
						'bool',
						"does the window float?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"modal",
						'pmod',
						'bool',
						"is the window modal?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"resizable",
						'prsz',
						'bool',
						"is the window resizable?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"zoomable",
						'iszm',
						'bool',
						"is the window zoomable?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"zoomed",
						'pzum',
						'bool',
						"is the window zoomed?",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"visible",
						'pvis',
						'bool',
						"is the window visible?",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"position",
						'ppos',
						'QDpt',
						"upper left coordinates of window",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"windows",
				'cwin',
				"every window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			

		},

		{
		},

		{
			
				'savo',
				{
					
						"yes",
						'yes ',
						"Save objects now"
					,
						"no",
						'no  ',
						"Do not save objects"
					,
						"ask",
						'ask ',
						"Ask the user whether to save"
					
				}
			
		}
	,
	"Rezilla suite",       	
	"Rezilla specifics",	
	'Rzil',         	
	1,      	
	1,    
	
		{						
			
				"compare",
				"compare two resource maps",
				'Rzil',
				'comp',
				'Mcmp',
				"a maps comparison object",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'alis',
				"first resource file for comparison",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"and",
						'AndF',
						'alis',
						"second resource file for comparison",
							required,
							singleItem,
							enumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"ignoreName",
						'IgnN',
						'bool',
						"ignore name differences",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"ignoreAttrs",
						'IgnA',
						'bool',
						"ignore attributes differences",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"ignoreData",
						'IgnD',
						'bool',
						"ignore data differences",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"delete",
				"Delete the specified object",
				'core',
				'delo',
				'null',
				"",
					replyOptional,
					singleItem,
					notEnumerated,
					notTightBindingFunction,
					enumsAreConstants,
					enumListCanRepeat,
					replyIsValue,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					verbEvent,
					reserved,
					reserved,
					reserved,
				'obj ',
				"the object to delete",
					directParamRequired,
					singleItem,
					notEnumerated,
					changesState,
					enumsAreConstants,
					enumListCanRepeat,
					directParamIsValue,
					directParamIsTarget,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
				{
				}
			,
				"duplicate",
				"Duplicate a resource in the resource map. The duplicate is automatically attributed an unique ID.",
				'core',
				'clon',
				'obj ',
				"a specifier for the duplicated resource(s)",
					replyRequired,
					singleItem,
					notEnumerated,
					notTightBindingFunction,
					enumsAreConstants,
					enumListCanRepeat,
					replyIsValue,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					verbEvent,
					reserved,
					reserved,
					reserved,
				'obj ',
				"the object to duplicate",
					directParamRequired,
					singleItem,
					notEnumerated,
					changesState,
					enumsAreConstants,
					enumListCanRepeat,
					directParamIsValue,
					directParamIsTarget,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
				{
				}
			,
				"edit",
				"edit one or more resources",
				'Rzil',
				'edit',
				'null',
				"",
				replyOptional,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'cRSC',
				"resource to edit",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"using",
						'usin',
						'EKND',
						"specifies which kind of editor to use (if not specified, Rezilla tries to find successively an interface, a template or the hexadecimal editor)",
							optional,
							singleItem,
							enumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"like",
						'Like',
						'type',
						"use an another type's editor",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"export",
				"export a rezmap document in a specified format",
				'Rzil',
				'expt',
				'null',
				"",
				replyOptional,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'MapD',
				"resource map document to export",
				directParamRequired,
				singleItem,
				notEnumerated,
				changesState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"in",
						'kfil',
						'alis',
						"the folder in which to save the export file. This folder must already exist.",
							required,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"with properties",
						'prdt',
						'reco',
						"the initial values for the properties (essentially to specify a name and a format)",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"inspect",
				"display info about the specified resource in the Inspector window",
				'Rzil',
				'insp',
				'null',
				"",
				replyOptional,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'cRSC',
				"Resource object to display info about.",
				directParamRequired,
				singleItem,
				notEnumerated,
				changesState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
				}
			

		},
		
		{
			
				"map document",
				'MapD',
				"a resource map document (representing the contents of an entire fork)",
				{
					
						"inherits",
						'c@#^',
						'docu',
						"all properties of the 'document' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"index",
						'pidx',
						'long',
						"the number of the document among other map documents",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"readOnly",
						'pRDO',
						'bool',
						"is this document read-only?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"window",
						'cwin',
						'cwin',
						"the window of the document.",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"refnum",
						'pRFN',
						'shor',
						"the reference number of the map in memory",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"fork",
						'pFRK',
						'FKND',
						"the fork this document is editing (data fork or resource fork)",
							reserved,
							singleItem,
							enumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"map",
						'cMAP',
						'cMAP',
						"the resource map associated with this document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"file",
						'pFIL',
						'fss ',
						"the file on disk corresponding to this resource map document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"format",
						'pFRM',
						'EXPF',
						"the format used for export",
							reserved,
							singleItem,
							enumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
					
						'EdiD',
						{
							'indx',
							'name'}
					
				}
			,
				"map documents",
				'MapD',
				"every map document",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"editor",
				'EdiD',
				"an editor document for a single resource",
				{
					
						"inherits",
						'c@#^',
						'docu',
						"all properties of the 'document' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"index",
						'pidx',
						'long',
						"the number of the document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"kind",
						'pKND',
						'EKND',
						"the kind of editor document (hexadecimal, template or interface)",
							reserved,
							singleItem,
							enumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"readOnly",
						'pRDO',
						'bool',
						"is this document read-only?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"window",
						'cwin',
						'cwin',
						"the window of the document.",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"resource",
						'cRSC',
						'cRSC',
						"the resource edited by this document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"owner doc",
						'pOWM',
						'MapD',
						"the rezmap document that owns this editor document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"editors",
				'EdiD',
				"every editor document",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"interface editor",
				'GuiD',
				"a dedicated interface document editing a resource",
				{
					
						"inherits",
						'c@#^',
						'EdiD',
						"all properties of the 'editor' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"interface editors",
				'GuiD',
				"every interface editor",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"template editor",
				'TmpD',
				"a template document editing a resource",
				{
					
						"inherits",
						'c@#^',
						'EdiD',
						"all properties of the 'editor' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"template editors",
				'TmpD',
				"every template editor",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"hexadecimal editor",
				'HexD',
				"a hexadecimal document editing a resource",
				{
					
						"inherits",
						'c@#^',
						'EdiD',
						"all properties of the 'editor' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"hexadecimal editors",
				'HexD',
				"every hexadecimal editor",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"map window",
				'MapW',
				"a resource map window",
				{
					
						"inherits",
						'c@#^',
						'cwin',
						"all properties of the 'window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"types count",
						'Tcnt',
						'long',
						"number of types in this map as displayed at the bottom of the map window",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"resources count",
						'Rcnt',
						'long',
						"total number of resources in this map as displayed at the bottom of the map window",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"map windows",
				'MapW',
				"every map window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"editing window",
				'EdiW',
				"a resource editing window (hexadecimal, template or interface)",
				{
					
						"inherits",
						'c@#^',
						'cwin',
						"all properties of the 'window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"kind",
						'pKND',
						'EKND',
						"the kind of the editing window (hexadecimal, template or interface)",
							reserved,
							singleItem,
							enumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"editing windows",
				'EdiW',
				"every editing window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"interface window",
				'GuiW',
				"an interface editing window",
				{
					
						"inherits",
						'c@#^',
						'EdiW',
						"all properties of the 'editing window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"interface windows",
				'GuiW',
				"every interface window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"template window",
				'TmpW',
				"a template editing window",
				{
					
						"inherits",
						'c@#^',
						'EdiW',
						"all properties of the 'editing window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"template windows",
				'TmpW',
				"every template window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"hexadecimal window",
				'HexW',
				"a hexadecimal editing window",
				{
					
						"inherits",
						'c@#^',
						'EdiW',
						"all properties of the 'editing window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"maxPos",
						'maxP',
						'long',
						"index of last position (i-e position after the last character)",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"startPos",
						'iniP',
						'long',
						"position of beginning of selection",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"endPos",
						'endP',
						'long',
						"position of end of selection",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"hex selection",
						'hSel',
						'itxt',
						"the contents of the selected region in the hex pane",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"text selection",
						'tSel',
						'itxt',
						"the contents of the selected region in the text pane",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"hexadecimal windows",
				'HexW',
				"every hexadecimal window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"comparison window",
				'CmpW',
				"a maps comparison window",
				{
					
						"inherits",
						'c@#^',
						'cwin',
						"all properties of the 'window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"result",
						'pRES',
						'Mcmp',
						"a comparison result object",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"comparison windows",
				'CmpW',
				"every comparison window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"inspector window",
				'InsW',
				"the inspector window",
				{
					
						"inherits",
						'c@#^',
						'cwin',
						"all properties of the 'window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"ID field",
						'pIDF',
						'shor',
						"the value of the 'ID' field",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"name field",
						'pNAF',
						'itxt',
						"the value of the 'name' field",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"system heap",
						'pSHP',
						'bool',
						"the value of the 'System Heap' checkbox",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"purgeable",
						'pPUR',
						'bool',
						"the value of the 'Purgeable' checkbox",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"locked",
						'pLOC',
						'bool',
						"the value of the 'Locked' checkbox",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"preload",
						'pPRE',
						'bool',
						"the value of the 'Preload' checkbox",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"protected",
						'pPRO',
						'bool',
						"the value of the 'Protected' checkbox",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"current resource",
						'pRSC',
						'cRSC',
						"the resource for which info is currently displayed",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			

		},
		
		{
		},
		
		{
			
				'EKND',
				{
					
						"hexadecimal",
						'EHEX',
						"hexadecimal editor"
					,
						"template",
						'ETMP',
						"template editor"
					,
						"interface",
						'EGUI',
						"dedicated interface editor"
					
				}
			,
				'PKND',
				{
					
						"hexadecimal",
						'HEXA',
						"hex pane"
					,
						"ascii",
						'ASCI',
						"text pane"
					
				}
			,
				'EXPF',
				{
					
						"unknown export",
						'UEXP',
						"unknown export format"
					,
						"xml",
						'XML ',
						"xml export format"
					,
						"html",
						'HTML',
						"html export format"
					,
						"text",
						'TEXT',
						"text export format"
					,
						"DeRez",
						'DREZ',
						"DeRez export format"
					
				}
			
		}
	,
	"Resource suite",       	
	"Resource maps handling",	
	'Rsrc',         	
	1,      	
	1,    
	
		{						
		},
		
		{
			
				"map",
				'cMAP',
				"a resource map",
				{
					
						"refnum",
						'pRFN',
						'shor',
						"the reference number of the map in memory",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"all types",
						'pTYL',
						'list',
						"the list of all types (in alphabetical order)",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"attributes",
						'pATR',
						'shor',
						"the global value of the map attributes (sum of the individual flags)",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"readOnly",
						'pRDO',
						'bool',
						"the mapReadOnly bit",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"compact",
						'pCPT',
						'bool',
						"the mapCompact bit",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"changed",
						'imod',
						'bool',
						"the mapChanged bit",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
					
						'cTYP',
						{
							'indx',
							'name',
							'ID  '}
					
				}
			,
				"maps",
				'cMAP',
				"every map",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"type",
				'cTYP',
				"a resource type",
				{
					
						"index",
						'pidx',
						'long',
						"the index of the type in the document (types are ordered alphabetically)",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"name",
						'pnam',
						'itxt',
						"the type's name",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"ID",
						'ID  ',
						'magn',
						"a type as a long unsigned integer",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"all IDs",
						'pIDL',
						'list',
						"the list of all IDs of resources belonging to this type",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
					
						'cRSC',
						{
							'name',
							'ID  ',
							'indx'}
					
				}
			,
				"types",
				'cTYP',
				"every type",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"resource",
				'cRSC',
				"a single resource with specific type and ID",
				{
					
						"name",
						'pnam',
						'itxt',
						"the resource's name",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"typename",
						'pTYP',
						'TEXT',
						"the type of the resource as text",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"ID",
						'ID  ',
						'shor',
						"the ID of the resource",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"index",
						'pidx',
						'long',
						"the index of the resource within its type (in the order used by the resource manager)",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"attributes",
						'pATR',
						'shor',
						"the global value of the resource attributes (sum of the individual flags)",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"sysHeap",
						'pSHP',
						'bool',
						"the resSysHeap bit",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"purgeable",
						'pPUR',
						'bool',
						"the resPurgeable bit",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"locked",
						'pLOC',
						'bool',
						"the resLocked bit",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"preload",
						'pPRE',
						'bool',
						"the resPreload bit",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"protected",
						'pPRO',
						'bool',
						"the resProtected bit",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"changed",
						'imod',
						'bool',
						"the resChanged bit",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"size",
						'pSIZ',
						'long',
						"the size of the resource data (in bytes)",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"sizeOnDisc",
						'pDSZ',
						'long',
						"the size of the resource on disk",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"hex data",
						'pDAT',
						'****',
						"the resource data (in hex format)",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"resources",
				'cRSC',
				"every resource",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"comparison",
				'Mcmp',
				"the result of a comparison between two maps",
				{
					
						"criteria",
						'pCRI',
						'reco',
						"the comparison criteria",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"ignoreName",
						'IgnN',
						'bool',
						"have name differences been ignored?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"ignoreAttrs",
						'IgnA',
						'bool',
						"have attributes differences been ignored?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"ignoreData",
						'IgnD',
						'bool',
						"have data differences been ignored?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"old only resources",
						'OldR',
						'list',
						"the list of resources which are only in the old map",
							reserved,
							listOfItems,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"new only resources",
						'NewR',
						'list',
						"the list of resources which are only in the new map",
							reserved,
							listOfItems,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"differing resources",
						'Diff',
						'list',
						"the list of resources which exist in both maps and are different",
							reserved,
							listOfItems,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"identical resources",
						'Iden',
						'list',
						"the list of resources which exist in both maps and are identical",
							reserved,
							listOfItems,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"specifier",
				'TyId',
				"a two-elements list containing the type and the ID of a resource",
				{
				},
				{
				}
			

		},
		
		{
		},
		
		{
			
				'FORK',
				{
					
						"data fork",
						'DATF',
						"map in data fork"
					,
						"resource fork",
						'RSRF',
						"map in resource fork"
					,
						"any fork",
						'ANYF',
						"could be any fork"
					,
						"same fork",
						'SAMF',
						"same fork (in a Save As operation)"
					
				}
			,
				'FKND',
				{
					
						"DataFork",
						'DFRK',
						"map lies in data fork"
					,
						"ResourceFork",
						'RFRK',
						"map lies in resource fork"
					,
						"UnknownFork",
						'UFRK',
						"fork is unknown"
					
				}
			
		}
	
	
}

};


