









#define SystemSevenOrLater 1
//#include "Types.r"
//#include "SysTypes.r"
//#include "AEUserTermTypes.r"
#include <Carbon/Carbon.r>

resource 'aete' (0,"Scripting terminology") {
0x1,
0x0,
0,
0,

{
	
	"Required Suite",       	
	"Terms that every application should support",	
	'reqd',         	
	1,      	
	1,    
		{
		},

		{
		},

		{
		},

		{
		}
	,
	"Standard Suite",
	"Common terms for most applications",
	'CoRe',
	1,
	1,
		{
			
				"close",
				"Close an object",
				'core',
				'clos',
				'null',
				"",
					replyOptional,
					singleItem,
					notEnumerated,
					notTightBindingFunction,
					enumsAreConstants,
					enumListCanRepeat,
					replyIsValue,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					verbEvent,
					reserved,
					reserved,
					reserved,
				'obj ',
				"the objects to close",
					directParamRequired,
					singleItem,
					notEnumerated,
					changesState,
					enumsAreConstants,
					enumListCanRepeat,
					directParamIsValue,
					directParamIsTarget,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
					reserved,
				{
					
						"saving",
						'savo',
						'savo',
						"specifies whether or not changes should be saved before closing",
							optional,
							singleItem,
							enumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"in",
						'kfil',
						'alis',
						"the file in which to save the object",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"count",
				"Return the number of elements of a particular class within an object",
				'core',
				'cnte',
				'long',
				"the number of elements",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"the object whose elements are to be counted",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"each",
						'kocl',
						'type',
						"the class of the elements to be counted",
							required,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
								paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"data size",
				"Return the size in bytes of an object",
				'core',
				'dsiz',
				'long',
				"the size of the object in bytes",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"the object whose data size is to be returned",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
				}
			,
				"exists",
				"Verify if an object exists",
				'core',
				'doex',
				'bool',
				"true if it exists, false if not",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'null',
				"",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
				}
			,
				"get",
				"Get the data for an object",
				'core',
				'getd',
				'****',
				"The data from the object",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"the object whose data is to be returned",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
				}
			,
				"make",
				"Make a new element",
				'core',
				'crel',
				'obj ',
				"Object specifier for the new element",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'null',
				"",
				directParamOptional,
				singleItem,
				notEnumerated,
				changesState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"new",
						'kocl',
						'type',
						"the class of the new element",
							required,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"at",
						'insh',
						'insl',
						"the location at which to insert the element",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"with data",
						'data',
						'****',
						"the initial data for the element",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"with properties",
						'prdt',
						'reco',
						"the initial values for the properties of the element",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"open",
				"Open the specified object(s)",
				'aevt',
				'odoc',
				'null',
				"",
				replyOptional,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"Objects to open. Can be a list of files or an object specifier.",
				directParamRequired,
				singleItem,
				notEnumerated,
				changesState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
				}
			,
				"save",
				"save a set of objects",
				'core',
				'save',
				'null',
				"",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"Objects to save.",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"in",
						'kfil',
						'alis',
						"the file in which to save the object(s)",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					,
						"as",
						'fltp',
						'type',
						"the file type of the document in which to save the data",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"set",
				"Set an object's data",
				'core',
				'setd',
				'null',
				"",
				replyOptional,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"the object to change",
				directParamRequired,
				singleItem,
				notEnumerated,
				changesState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"to",
						'data',
						'****',
						"the new value",
							required,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			

		},

		{
			
				"application",
				'capp',
				"the application",
				{
					
						"name",
						'pnam',
						'itxt',
						"Rezilla's name",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"version",
						'vers',
						'itxt',
						"the version of the application",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"clipboard",
						'pcli',
						'obj ',
						"Rezilla's private clipboard",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"preferences",
						'pfrp',
						'obj ',
						"Various preferences that apply to the application as a whole",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
					
						'cwin',
						{
							'indx',
							'name',
							'rang'}
					,
						'docu',
						{
							'indx',
							'name'}
					,
						'MapD',
						{
							'indx',
							'name'}
					
				}
			,
				"document",
				'docu',
				"A document",
				{
					
						"name",
						'pnam',
						'itxt',
						"the title of the document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"modified",
						'imod',
						'bool',
						"Has the document been modified since the last save?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"documents",
				'docu',
				"every document",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"window",
				'cwin',
				"a window",
				{
					
						"name",
						'pnam',
						'itxt',
						"the title of the window",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"index",
						'pidx',
						'long',
						"the number of the window",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"bounds",
						'pbnd',
						'qdrt',
						"the boundary rectangle for the window",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"closeable",
						'hclb',
						'bool',
						"Does the window have a close box?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"titled",
						'ptit',
						'bool',
						"Does the window have a title bar?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"floating",
						'isfl',
						'bool',
						"Does the window float?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"modal",
						'pmod',
						'bool',
						"Is the window modal?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"resizable",
						'prsz',
						'bool',
						"Is the window resizable?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"zoomable",
						'iszm',
						'bool',
						"Is the window zoomable?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"zoomed",
						'pzum',
						'bool',
						"Is the window zoomed?",
							reserved,
							singleItem,
							notEnumerated,
							readWrite,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"visible",
						'pvis',
						'bool',
						"is the window visible?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"position",
						'ppos',
						'QDpt',
						"upper left coordinates of window",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"windows",
				'cwin',
				"every window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			

		},

		{
		},

		{
			
				'savo',
				{
					
						"yes",
						'yes ',
						"Save objects now"
					,
						"no",
						'no  ',
						"Do not save objects"
					,
						"ask",
						'ask ',
						"Ask the user whether to save"
					
				}
			
		}
	,
	"Miscellaneous Suite",
	"Useful events that aren't in standard suite",
	'misc',
	0,
	0,
		{
			
				"revert",
				"Revert an object to the most recently saved version",
				'misc',
				'rvrt',
				'null',
				"",
				replyOptional,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"object to revert",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
				}
			,
				"SetTellTarget",
				"Makes an object the 'focus' of AppleEvents",
				'ppnt',
				'sttg',
				'null',
				"",
				replyRequired,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'null',
				"",
				directParamRequired,
				singleItem,
				notEnumerated,
				doesntChangeState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
					
						"to",
						'data',
						'obj ',
						"reference to new focus of AppleEvents",
							optional,
							singleItem,
							notEnumerated,
							reserved,
							enumsAreConstants,
							enumListCanRepeat,
							paramIsValue,
							notParamIsTarget,
							reserved,
							reserved,
							reserved,
							reserved,
							prepositionParam,
							notFeminine,
							notMasculine,
							singular
					
				}
			,
				"select",
				"Select the specified object",
				'misc',
				'slct',
				'null',
				"",
				replyOptional,
				singleItem,
				notEnumerated,
				notTightBindingFunction,
				enumsAreConstants,
				enumListCanRepeat,
				replyIsValue,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				verbEvent,
				reserved,
				reserved,
				reserved,
				'obj ',
				"the object to select",
				directParamOptional,
				singleItem,
				notEnumerated,
				changesState,
				enumsAreConstants,
				enumListCanRepeat,
				directParamIsValue,
				directParamIsTarget,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				reserved,
				{
				}
			

		},

		{
		},

		{
		},

		{
		}
	,
	"Rezilla suite",       	
	"Rezilla specifics",	
	'Rzil',         	
	1,      	
	1,    
	
		{						
		},
		
		{
			
				"map document",
				'MapD',
				"a resource map document (representing the contents of an entire fork)",
				{
					
						"inherits",
						'c@#^',
						'docu',
						"all properties of the 'document' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"index",
						'pidx',
						'long',
						"the number of the document among other map documents",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"readOnly",
						'pRDO',
						'bool',
						"Is this document read-only?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"window",
						'cwin',
						'cwin',
						"the window of the document.",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"refnum",
						'pRFN',
						'shor',
						"the reference number of the map in memory",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"fork",
						'pFRK',
						'FORK',
						"the fork this document is editing (data fork or resource fork)",
							reserved,
							singleItem,
							enumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"map",
						'cMAP',
						'cMAP',
						"the resource map associated with this document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"file",
						'pFIL',
						'fss ',
						"the file on disk corresponding to this resource map document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
					
						'EdiD',
						{
							'indx',
							'name'}
					
				}
			,
				"map documents",
				'MapD',
				"every map document",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"editor document",
				'EdiD',
				"an editor document for a single resource",
				{
					
						"inherits",
						'c@#^',
						'docu',
						"all properties of the 'document' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"index",
						'pidx',
						'long',
						"the number of the document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"kind",
						'pKND',
						'EKND',
						"the kind of editor document (hexadecimal, template or interface)",
							reserved,
							singleItem,
							enumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"readOnly",
						'pRDO',
						'bool',
						"Is this document read-only?",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"window",
						'cwin',
						'cwin',
						"the window of the document.",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"resource",
						'cRSC',
						'cRSC',
						"the resource edited by this document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"owner doc",
						'pOWM',
						'MapD',
						"the rezmap document that owns this editor document",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"editor documents",
				'EdiD',
				"every editor document",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"interface document",
				'GuiD',
				"a dedicated interface document editing a resource",
				{
					
						"inherits",
						'c@#^',
						'EdiD',
						"all properties of the 'editor document' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"interface documents",
				'GuiD',
				"every interface document",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"template document",
				'TmpD',
				"a template document editing a resource",
				{
					
						"inherits",
						'c@#^',
						'EdiD',
						"all properties of the 'editor document' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"template documents",
				'TmpD',
				"every template document",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"hex document",
				'HexD',
				"a hexadecimal document editing a resource",
				{
					
						"inherits",
						'c@#^',
						'EdiD',
						"all properties of the 'editor document' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"hex documents",
				'HexD',
				"every hex document",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"map window",
				'MapW',
				"a resource map window",
				{
					
						"inherits",
						'c@#^',
						'cwin',
						"all properties of the 'window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"map windows",
				'MapW',
				"every map window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"editor window",
				'EdiW',
				"a resource editor window (hexadecimal, template or interface)",
				{
					
						"inherits",
						'c@#^',
						'cwin',
						"all properties of the 'window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"kind",
						'pKND',
						'EKND',
						"the kind of the editor window (hexadecimal, template or interface)",
							reserved,
							singleItem,
							enumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"editor windows",
				'EdiW',
				"every editor window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"interface window",
				'GuiW',
				"an interface editor window",
				{
					
						"inherits",
						'c@#^',
						'EdiW',
						"all properties of the 'editor window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"interface windows",
				'GuiW',
				"every interface window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"template window",
				'TmpW',
				"a template editor window",
				{
					
						"inherits",
						'c@#^',
						'EdiW',
						"all properties of the 'editor window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"template windows",
				'TmpW',
				"every template window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"hex window",
				'HexW',
				"a hexadecimal editor window",
				{
					
						"inherits",
						'c@#^',
						'EdiW',
						"all properties of the 'editor window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"hex pane",
						'HexP',
						'DatP',
						"the left pane of the hex window",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"text pane",
						'TxtP',
						'DatP',
						"the left pane of the hex window",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"hex windows",
				'HexW',
				"every hex window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"comparison window",
				'CmpW',
				"a maps comparison window",
				{
					
						"inherits",
						'c@#^',
						'cwin',
						"all properties of the 'window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"result",
						'pRES',
						'COMP',
						"a comparison result object",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"comparison windows",
				'CmpW',
				"every comparison window",
				{
					
						"",
						'c@#!',
						'type',
						"",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							plural
					
				},
				{
				}
			,
				"inspector",
				'Insp',
				"the inspector window",
				{
					
						"inherits",
						'c@#^',
						'cwin',
						"all properties of the 'window' class",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			,
				"data pane",
				'DatP',
				"a pane displaying resource data",
				{
					
						"kind",
						'pKND',
						'PKND',
						"the kind of data this pane displays (hexadecimal or ascii text)",
							reserved,
							singleItem,
							enumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					,
						"contents",
						'pcnt',
						'TEXT',
						"the data displayed in this pane",
							reserved,
							singleItem,
							notEnumerated,
							readOnly,
							enumsAreConstants,
							enumListCanRepeat,
							propertyIsValue,
							reserved,
							reserved,
							reserved,
							reserved,
							reserved,
							noApostrophe,
							notFeminine,
							notMasculine,
							singular
					
				},
				{
				}
			

		},
		
		{
		},
		
		{
			
				'DKND',
				{
					
						"resource map",
						'RMAP',
						"a resource map document"
					,
						"resource editor",
						'EDOC',
						"a resource editor"
					,
						"maps comparison",
						'COMP',
						"a maps comparison document"
					
				}
			,
				'EKND',
				{
					
						"hexadecimal",
						'EHEX',
						"hexadecimal editor"
					,
						"template",
						'ETMP',
						"template editor"
					,
						"interface",
						'EGUI',
						"dedicated interface editor"
					
				}
			,
				'PKND',
				{
					
						"hexadecimal",
						'HEXA',
						"hex pane"
					,
						"ascii",
						'ASCI',
						"text pane"
					
				}
			
		}
	,
	"Resource suite",       	
	"Resource maps handling",	
	'Rsrc',         	
	1,      	
	1,    
	
		{						
		},
		
		{
			
				"map",
				'cMAP',
				"a resource map",
				{
					
						"refnum",
						'pRFN',
						'shor',
						"the reference number of the map in memory",
						reserved,
						singleItem,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"attributes",
						'pATR',
						'shor',
						"the global value of the map attributes (sum of the individual flags)",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"readOnly",
						'pRDO',
						'bool',
						"the mapReadOnly bit",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"compact",
						'pCPT',
						'bool',
						"the mapCompact bit",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"changed",
						'imod',
						'bool',
						"the mapChanged bit",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					
				},
				{
					
						'cTYP',
						{
							'indx',
							'name',
							'list'}
					,
						'cRSC',
						{
							'indx',
							'list'}
					
				}
			,
				"maps",
				'cMAP',
				"every map",
				{
					
						"",
						'c@#!',
						'type',
						"",
						reserved,
						singleItem,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						plural
					
				},
				{
				}
			,
				"type",
				'cTYP',
				"a resource type",
				{
					
						"name",
						'pnam',
						'itxt',
						"the type's name",
						reserved,
						singleItem,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					
				},
				{
					
						'cRSC',
						{
							'name',
							'ID  ',
							'indx'}
					
				}
			,
				"types",
				'cTYP',
				"every type",
				{
					
						"",
						'c@#!',
						'type',
						"",
						reserved,
						singleItem,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						plural
					
				},
				{
				}
			,
				"resource",
				'cRSC',
				"a single resource",
				{
					
						"name",
						'pnam',
						'itxt',
						"the map's name",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"type",
						'pTYP',
						'TEXT',
						"the type of the resource",
						reserved,
						singleItem,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"ID",
						'ID  ',
						'shor',
						"the ID of the resource",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"specifier",
						'pSPE',
						'TyId',
						"the (type,ID) pair (which can be useful to characterize this resource)",
						reserved,
						singleItem,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"attributes",
						'pATR',
						'shor',
						"the global value of the resource attributes (sum of the individual flags)",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"sysHeap",
						'pSHP',
						'bool',
						"the resSysHeap bit",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"purgeable",
						'pPUR',
						'bool',
						"the resPurgeable bit",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"locked",
						'pLOC',
						'bool',
						"the resLocked bit",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"resPreload",
						'pPRE',
						'bool',
						"the resPreload bit",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"protected",
						'pPRO',
						'bool',
						"the resProtected bit",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"changed",
						'imod',
						'bool',
						"the resChanged bit",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"size",
						'pSIZ',
						'long',
						"the size of the resource data (in bytes)",
						reserved,
						singleItem,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"sizeOnDisc",
						'pDSZ',
						'long',
						"the size of the resource on disk",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"data",
						'pcnt',
						'****',
						"the resource data (in hex format)",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					
				},
				{
				}
			,
				"resources",
				'cRSC',
				"every resource",
				{
					
						"",
						'c@#!',
						'type',
						"",
						reserved,
						singleItem,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						plural
					
				},
				{
				}
			,
				"comparison",
				'COMP',
				"the result of a comparison between two maps",
				{
					
						"criteria",
						'pCRI',
						'reco',
						"the comparison criteria",
						reserved,
						singleItem,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"old only resources",
						'OldR',
						'TyId',
						"resources which are only in the old map",
						reserved,
						listOfItems,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"new only resources",
						'NewR',
						'TyId',
						"resources which are only in the new map",
						reserved,
						listOfItems,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"differing resources",
						'Diff',
						'TyId',
						"resources which are in both maps and are different",
						reserved,
						listOfItems,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"identical resources",
						'Iden',
						'TyId',
						"resources which are in both maps and are identical",
						reserved,
						listOfItems,
						notEnumerated,
						readOnly,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					
				},
				{
				}
			,
				"specifier",
				'TyId',
				"a record containing the type and the ID of a resource",
				{
					
						"type",
						'pTYP',
						'TEXT',
						"a resource's type",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					,
						"ID",
						'ID  ',
						'shor',
						"a resource's ID",
						reserved,
						singleItem,
						notEnumerated,
						readWrite,
						enumsAreConstants,
						enumListCanRepeat,
						propertyIsValue,
						reserved,
						reserved,
						reserved,
						reserved,
						reserved,
						noApostrophe,
						notFeminine,
						notMasculine,
						singular
					
				},
				{
				}
			

		},
		
		{
		},
		
		{
			
				'FORK',
				{
					
						"dataFork",
						'DATF',
						"map in data fork"
					,
						"resourceFork",
						'RSRF',
						"map in resource fork"
					,
						"anyFork",
						'ANYF',
						"could be any fork"
					
				}
			,
				'FKND',
				{
					
						"data fork",
						'DFRK',
						"map lies in data fork"
					,
						"resource fork",
						'RFRK',
						"map lies in resource fork"
					,
						"unknown fork",
						'UFRK',
						"fork is unknown"
					
				}
			
		}
	
	
}

};


